stages:
  - build
  - push
  - deploy

variables:
  DOCKER_HOST: "tcp://docker:2375/"
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.12-dind

before_script:
  - docker info

build-push-and-deploy:
  image: docker:latest
  stage: build
  script:
    - echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
    - docker buildx create --use
    - docker buildx inspect --bootstrap
    - docker build -t solmos034/symfony_devops_project:php8-sf6 ./php8-sf6
    - docker push solmos034/symfony_devops_project:php8-sf6
    - docker-compose up -d
    - |
      CONTAINER_ID=$(docker-compose ps -q database)
      docker commit $CONTAINER_ID solmos034/symfony_devops_project:database
      docker push solmos034/symfony_devops_project:database
    - |
      CONTAINER_ID=$(docker-compose ps -q mailer)
      docker commit $CONTAINER_ID solmos034/symfony_devops_project:mailer
      docker push solmos034/symfony_devops_project:mailer
    - minikube start --driver=docker
    - kubectl create namespace symfony-namespace --dry-run=client -o yaml | kubectl apply -f -
    - minikube status
    - kubectl config current-context
    - kubectl apply -f k8s/services.yml --dry-run=client
    - kubectl apply -f k8s/services.yml -n symfony-namespace --validate=false

after_script:
  - echo "Workflow ran successfully!"
