# docker-compose file

version: "3.7"
# les services
services:
  # php
  php8-sf6:
    container_name: php8-sf6
    build: php8-sf6
    ports:
      - "9000:8000"
    volumes:
      - ./project:/var/www/html
  # mailer
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
  # database
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: ChangeMe
      POSTGRES_USER: symfony
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432"
# volumes
volumes:
  db-data:
