# CD workflow
name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull php8-sf6 image from Docker Hub
        run: docker pull solmos034/symfony_devops_project:php8-sf6

      - name: Pull database image from Docker Hub
        run: docker pull solmos034/symfony_devops_project:database

      - name: Pull mailer image from Docker Hub
        run: docker pull solmos034/symfony_devops_project:mailer

      - name: Deploy services using Docker Compose
        run: |
          docker-compose down
          docker-compose build
          docker-compose up -d

      - name: Notify on deployment success
        run: echo "Deployment to production was successful."
