name: Deploy to Kubernetes

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/ --namespace symfony-namespace  # ajustez le chemin vers vos fichiers YAML Kubernetes

      - name: Display Success Message
        run: echo "Workflow ran successfully!"
