# CI WORKFLOW
name: Build and Push Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push php8-sf6 image
        uses: docker/build-push-action@v2
        with:
          context: ./php8-sf6
          file: ./php8-sf6/Dockerfile
          push: true
          tags: solmos034/symfony_devops_project:php8-sf6


      - name: Display Success Message
        run: echo "Workflow ran successfully!"
